class Constants():
    
    ONLY_ONE_SOLUTION = False

    PROJECTOR_ROUNDING = 10

    AND_PARSER_OPERATOR = "&"
    OR_PARSER_OPERATOR = "|"
    NOT_PARSER_OPERATOR = "~"
    XOR_PARSER_OPERATOR = "<+>"
    IMPLICATION_PARSER_OPERATOR = "->"
    EQUIVALENCE_PARSER_OPERATOR = "<->"

    LINEAR_CONSTRAINT_STRING_DISPLAY_MULT = True

    AND_STRING_OPERATOR = "&"
    OR_STRING_OPERATOR = "|"
    NOT_STRING_OPERATOR = "~"
    XOR_STRING_OPERATOR = "XOR"
    IMPLICATION_STRING_OPERATOR = "->"
    EQUIVALENCE_STRING_OPERATOR = "<->"
    TOP_STRING_OPERATOR = "TOP"
    BOTTOM_STRING_OPERATOR = "BOT"

    AND_LATEX_OPERATOR = "\\land"
    OR_LATEX_OPERATOR = "\\lor"
    NOT_LATEX_OPERATOR = "\\lnot"
    XOR_LATEX_OPERATOR = "\\oplus"
    IMPLICATION_LATEX_OPERATOR = "\\rightarrow"
    EQUIVALENCE_LATEX_OPERATOR = "\\leftrightarrow"
    TOP_LATEX_OPERATOR = "\\top"
    BOTTOM_LATEX_OPERATOR = "\\bot"
    EQ_LATEX_OPERATOR = "="
    LEQ_LATEX_OPERATOR = "\\leqslant"
    GEQ_LATEX_OPERATOR = "\\geqslant"