class Constants():
    
    ONLY_ONE_SOLUTION = True
    AND_PARSER_OPERATOR = "&"
    OR_PARSER_OPERATOR = "|"
    NOT_PARSER_OPERATOR = "~"
    XOR_PARSER_OPERATOR = "<-/->"
    IMPLICATION_PARSER_OPERATOR = "->"
    EQUIVALENCE_PARSER_OPERATOR = "<->"